config-version: 2

name: stephans_snow_sandbox
version: 2.0
profile: tpch

model-paths:
  - models
test-paths:
  - tests
docs-paths:
  - docs
seed-paths:
  - data
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
on-run-start:
  - alter warehouse transforming set warehouse_size=small;
  - '{{create_udfs()}}'
on-run-end:
  - alter warehouse transforming set warehouse_size=xsmall;
  - "{{ grant_all_on_schemas(schemas, 'transformer') }}"
vars:
  start_date: '1999-01-01'
  test: 'false'
  fct_order_items: mock_source__fct_order_items
  dbt_metrics_calendar_model: all_days
models:
  +automatic_clustering: true
  +query_tag: stephan-sandbox
  +persist_docs:
    relation: true
    columns: true
  +copy_grants: true
  +grants:
    select:
      - transformer
  stephans_snow_sandbox:
    staging:
      +group: data_engineering
      +materialized: view
    marts:
      +group: bi_team
      core:
        +materialized: table
snapshots:
  stephans_snow_sandbox:
    +schema: "{% if target.name == 'prod' %}snaps{% else %}{{ target.schema }}{% endif %}"
seeds:
  stephans_snow_sandbox:
    snowflake_contract_rates:
      +column_types:
        effective_date: DATE
        rate: NUMBER
flags:
  require_generic_test_arguments_property: true
